### ISSUE TITLE
TWINT archived?

### ISSUE THREAD

**Issue by Anonymous941** [twintproject/twint-zero#10]
Apologies for using this repo but all of the others are archived.  Why is this?  I couldn't find anything online about it being discontinued.

**Comment by pielco11** [comment]
No problem, @Anonymous941 , no need to apologise.

In reply to your question: that's because I couldn't (and cannot now too) find time to maintain it.

Here is a reference about this: https://twitter.com/noneprivacy/status/1505099788710207490

**Comment by Anonymous941** [comment]
Okay, thanks for maintaining the project for as long as you did.
