### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by jiatern** [twintproject/twint-zero#14]
Hi, it was working perfectly fine yesterday but all queries returned empty output today.

I tried even the simplest query such as: `go run main.go -Query "(from:username) since:2023-04-25"` and still get an empty output.

Tried on my ubuntu VPS and another Windows 11 machine.

EDIT: Okay I think I found the reason, seems like Twitter restricted search function to only registered users. This affects nitter's search too. See https://github.com/zedeus/nitter/issues/852

**Comment by archy-bold** [comment]
There's a PR on nitter (https://github.com/zedeus/nitter/pull/830) to provide login credentials to your instance. It's actually to remove the 18+ filter, but apparently it also works to unlock the search.

Given this, and the recommendation that twint doesn't scrape public instances, it looks like the only way to use this is going to be to host a nitter instance and run twint alongside. I'm going to spend some time next week looking into that and I'll post an update.

**Comment by pielco11** [comment]
Closing this because the issue doesn't exist anymore.

Please feel free to re-open with a comment in case the situation is not reflected on your side
