### ISSUE TITLE
Is there a way to export scrape results?

### ISSUE THREAD

**Issue by pipinstallpotato** [twintproject/twint-zero#16]
I'm unable to find a way to export the results to a directory path in the form of a file, changing the format only changes how the information is displayed in the terminal. I'd also like to know if this can be modified to allow video and image files to be archived.

**Comment by archy-bold** [comment]
You just use standard output redirection functions on the command line ie:

```bash
go run main.go -Query $QUERY -Instance $INSTANCE -Format $FORMAT > file.csv
```

Video and image files should already be included, although the URL may be slightly malformed, which should be [fixed by this PR](https://github.com/twintproject/twint-zero/pull/15).
