### ISSUE TITLE
if twint is discontinued , can you recommend another pakage with the same capabilities ? 

### ISSUE THREAD

**Issue by Sandy4321** [twintproject/twint-zero#17]
main twint is discontinued
but is this zero twint working 

if twint is discontinued , can you recommend another pakage with the same capabilities ?

**Comment by pielco11** [comment]
@Sandy4321 , as of now I'm not aware of any tool that replaces Twint at 100%

You may have to write middlewares by yourself, which would turn out in a mean to learn something new and I totally encourage you to proceed this way!
