### ISSUE TITLE
"If you compiled... well at this point you are supposed to know."

### ISSUE THREAD

**Issue by HyperCrowd** [twintproject/twint-zero#19]
I don't know GoLang, what is this supposed to mean?

**Comment by pielco11** [comment]
Hi @HyperCrowd , I invite you to have a look at Golang documentation. In the mean time all you have to know that once you compiled, you have an executable so the usage is something like `./executable --args...`

**Comment by HyperCrowd** [comment]
Thanks.  Sounds simple enough.  I just assumed it was some inside GoLang culture thing you were referencing. :p
