### ISSUE TITLE
[ISSUE] no tweets are being returned

### ISSUE THREAD

**Issue by avisekksarma** [twintproject/twint-zero#21]
I just tried this tool today after i tried like a week ago. But this time after running ```go run main.go -Query $QUERY``` ,it is not returning any output in terminal , just pauses for like 2 seconds then prints nothing.
![Screenshot from 2023-07-02 23-14-08](https://github.com/twintproject/twint-zero/assets/56149664/d2467864-51f8-40ac-998b-470efeecff7d)
 
Does this problem have anything to do with what twitter is trying to do like maybe stop scraping ?

**Comment by pielco11** [comment]
Hello @avisekksarma ,

as you may be aware of the recent news, there are some issues regarding accessing Twitter feeds for non-auth users.

The situation is being monitored and we hope it'll be restored as soon as possible.


FP

**Comment by pielco11** [comment]
The issue is partially resolved. Now we are able to get tweets however the time-frame is very limited to the most recent days.
