### ISSUE TITLE
Getting "status code error: 403 403 Forbidden"

### ISSUE THREAD

**Issue by XtremMaker** [twintproject/twint-zero#25]
Hello, i'm having a issue since this morning (Spain), and i don't really know what to do.

I want to execute this command: 
`go run main.go -Query "from:elonmusk since:2023-08-31" -Instance "nitter.net" -Format "csv" > tweets.csv`

As you can see, it's nothing too complicated, but when i execute that line, it appears this error: 
`status code error: 403 403 Forbidden`

I've been using this tool for something like a week and i didn't have any issues, i don't know why it happens now.

It's a general error o i'm doing something wrong? Thank you!

**Comment by XtremMaker** [comment]
Just for add context, the forbidden error continues with the url of nitter.net, like this "https://nitter.net/search?f=tweet&q=from%3Aelonmusk+since%3A2023-08-31", and in their website works fine.

**Comment by archy-bold** [comment]
I'd guess you've been blocked for scraping from a public Nitter instance. You should set up your own nitter instance and use that, as is mentioned in the readme.

**Comment by XtremMaker** [comment]
Oh okay, didn't thought about that. I'll give it a try tomorrow.  Thank you for the quick answer!
