### ISSUE TITLE
Multiple words search not working

### ISSUE THREAD

**Issue by Ramizworking** [twintproject/twint-zero#4]
Hello there,

The issue I am facing is using getting tweets only containing 2 or 3 words

For exemple when I use 

go run main.go -Query (flex working)

It gives me every tweets containing the word 'flex' but not the word working :

![image](https://user-images.githubusercontent.com/121347041/211772011-92db4372-37de-4633-b84b-ff80ecb29d14.png)

And then when I click on the link as you can see above here is what I get 👍 
![image](https://user-images.githubusercontent.com/121347041/211772169-a983acd6-11ee-4ded-8a37-4531c8dda4ef.png)

If you have an idea on how we could fix that ! Thanks

**Comment by pielco11** [comment]
Perhaps there was an error in the way inputs were parsed, but now it's working as expected. May you check now, please?

![image](https://user-images.githubusercontent.com/17363750/225922702-b29d4d76-3eb3-4c25-ae02-9a6a1cedaeef.png)

**Comment by archy-bold** [comment]
Maybe try quoting your query?

```bash
$ go run main.go -Query "(flex working)"
```

**Comment by pielco11** [comment]
There was an issue with the safe-url-encoding of the input. Now it's expected to work as needed.

(btw nice formatting is very welcome, not mandatory but please)
