### ISSUE TITLE
Exporting content results into csv

### ISSUE THREAD

**Issue by mnetzler** [twintproject/twint-zero#9]
I'm running the command: 

go run main.go -Query "Oath Keepers" -Instance nitter.moo moo.me -Format csv 

How do I export the results I get?

**Comment by archy-bold** [comment]
You can redirect the output to a file with:

```bash
go run main.go -Query "Oath Keepers" -Instance nitter.moo moo.me -Format csv > tweets.csv
```

**Comment by mnetzler** [comment]
@archy-bold thank you for your response. That provided me with a link to where I could see all the tweets, which was definitely helpful. However, I thought I would receive the results in a csv file. If the results were exported to a csv file, I have no idea where on my computer it went. I am using terminal through Ubuntu if that makes a difference.

**Comment by archy-bold** [comment]
Your instance URL is not valid.

Note: this query will run indefinitely so you'll need to interrupt the execution at some point with Ctrl + C.

**Comment by mnetzler** [comment]
@archy-bold why is my instance not valid? Do I need to include the space like you did in your initial response?

**Comment by pielco11** [comment]
@mnetzler your instance is not valid because `nitter.moo moo.me` is not a valid domain name

**Comment by mnetzler** [comment]
@pielco11 when I go to the instance link for nitter, it shows nitter.moomoo.me as an option for US. (See screenshot). Am I missing something? ![image](https://user-images.githubusercontent.com/60672048/233653863-060f3358-089a-4f4b-800b-ae39be9d68c4.jpeg)

**Comment by pielco11** [comment]
Dear @mnetzler ,

so it seems that the correct domain name is `nitter.moomoo.me` and not `nitter.moo moo.me` as you stated with the comment opening issue

Just a typo, nothing much


Please also consider this #12 (TLDR: this tool is broken)

**Comment by mnetzler** [comment]
I didn't even realize my typo. Thank you so much for your help!
